#if !defined(AFX_CLOCK_H__FEC092E6_CBCB_4A91_885E_2B55375CBEA7__INCLUDED_)
#define AFX_CLOCK_H__FEC092E6_CBCB_4A91_885E_2B55375CBEA7__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CClock wrapper class

class CClock : public CWnd
{
protected:
	DECLARE_DYNCREATE(CClock)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x8a7fcd0f, 0xfd34, 0x4bb0, { 0xa5, 0x7d, 0x70, 0x7b, 0xf1, 0xe1, 0x8f, 0x93 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	OLE_COLOR GetBackColor();
	void SetBackColor(OLE_COLOR);
	OLE_COLOR GetForeColor();
	void SetForeColor(OLE_COLOR);
	short GetInterval();
	void SetInterval(short);

// Operations
public:
	void Hello();
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CLOCK_H__FEC092E6_CBCB_4A91_885E_2B55375CBEA7__INCLUDED_)
